import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

export default defineConfig([
  ...nextVitals,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "public/images/**",
    // Generated by the Payload CLI
    "payload-types.ts",
    "migrations/**",
    "app/(payload)/admin/importMap.js",
  ]),
]);
